### ISSUE TITLE
Partial Search Bug.

### ISSUE THREAD

**Issue by nuttikung** [dtboy1995/mongoose-sex-page#2]
#### Issue description
I try to plugin this to my mongoose and it's working as normally but when I do with partial search such as modelOne.find({ 'comment': /hello/i }) it's not working as expected.

#### Steps to reproduce the issue

1.  Define Model
2. Find documents that contain with text as hello in comment path
3. Check the result

_Note : I use global plugin to inject req.query for this test._

#### What's the expected result?

- The result should count all and divided for calculate as pages
- Screenshot (2) 'pages' should be 2.

#### What's the actual result?

- The result is not count all and not calculate pages
- Screenshot (2) 'pages' is 1.

#### Additional details / screenshot

<img width="194" alt="screen shot 2018-06-03 at 01 43 24" src="https://user-images.githubusercontent.com/8456620/40879790-b51d67b4-66cf-11e8-84a4-908712fe1c6e.png">
<img width="199" alt="screen shot 2018-06-03 at 01 43 35" src="https://user-images.githubusercontent.com/8456620/40879791-b56db43a-66cf-11e8-88e5-f8d8d82dcd66.png">

**Comment by dtboy1995** [comment]
@nuttikung I'm very sorry for not replying in time, because of the time difference
can you show me your code? or give me some of your test data, and I'll write some code to test them.

**Comment by dtboy1995** [comment]
@nuttikung . the reason may be
in src `pagnation.coffee`
```coffeescript
promiseCount = @model
        .where @condition # in this line: maybe -> .where({})
        .count()
        .exec()

if @no_limit
        promiseRecords = @model
          .find @condition
else
        promiseRecords = @model
          .find @condition
          .skip skip
          .limit +@count
```
PS The `query` and `count all` of this library are based on query conditions.
my thinking at the time was to use a query condition as a prerequisite for pagination under that condition
bro, I need to check your code to help you solve this problem

**Comment by nuttikung** [comment]
Thanks for your feedback @dtboy1995 

It's working as expected, I was misunderstanding with api.

Could you please add example for condition case as my understand as below

```js
import mongoose from 'mongoose'
const Schema = mongoose.Schema
const schema = new Schema({
  comment: {
    text: {
      type: String,
      required: true,
    }
  }
}, {
    timestamps: { createdAt: 'created_at', updatedAt: 'updated_at' }
  }
)


export default connection.model(`comment`, schema)
```

Correct Way
```js
P(Comment).find({ 'text': hello/i }).inject(req.query).exec().then(function (result) {
 // your result is here.
})
```

Incorrect 
```js
P(Comment.find({ 'text': hello/i })).inject(req.query).exec().then(function (result) {
 // your result is here.
})
```

**Comment by dtboy1995** [comment]
@nuttikung of course, you can submit some pull request.

**Comment by dtboy1995** [comment]
i think i should use es6 to rewrite this tools，coffeescript was bad in communication

**Comment by dtboy1995** [comment]
please give me some advice to modify example.
